### ISSUE TITLE
As user, SignUp to the System

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#12]
Backend by @itsdgbro 
Frontend by @sajanshres @abhinaya000

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/54583d2b-a100-44b0-bd0f-76dd7770a6bf)

@RoDahal Here the boxes that are containing different fields like email, password have the different box size. So, make it identical.
