### ISSUE TITLE
As admin, be able to view the book request 

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#20]
Backend @itsdgbro

**Comment by itsdgbro** [comment]
Completed.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/aeebc6ae-fd79-4cf5-8eed-853638e9822a)

Here, instead of displaying username in admin dashboard book id is displayed . Please work on that
