### ISSUE TITLE
Home, Admin, User Dashboard CSS bug

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#27]
Make it more user friendly 
@RoDahal

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/82db795f-21e8-4dd2-b1ed-dd5cbf3d09d9)

@itsdgbro when the admin click on the setting, display the edit profile details instead of leaving it empty at the first glance. Other can be places as it is placed now.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/4fd620e3-385e-474d-aac4-f08090b3f1cf)

@RoDahal shift the highlighted area to the little right and make the font color white. The highlighted bar should be in green color so that the font white can be visible.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/c37cb6b0-f19c-4d11-9420-2176d8b1e04e)

@RoDahal the yellow and red highlights that are at the down. Make the sentence's alignment at the same level. And the red home highlight that is in the above either remove it or make the font size large.
