### ISSUE TITLE
Backend Testing

### ISSUE THREAD

**Issue by RekhaTheeng1014** [swastikabasnet/LibraryManagementSystem#31]
This is the testing of the application by BA @RekhaTheeng1014 in the backend (@itsdgbro) part.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/cbdd5041-cc9a-4924-9e71-f1b4c21352bc)

In username field, book id is displayed. So, fix it.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/d2b9efcd-3401-4a55-bc41-ea1bfc1e1c50)

Quantity of the book cannot be the negative value. And here it is going negative. So, fix it and make it error free

**Comment by itsdgbro** [comment]
<img width="1031" alt="Screenshot 2023-05-10 192135" src="https://github.com/swastikabasnet/LibraryManagementSystem/assets/94692679/e5d7952a-60a8-4d10-bff2-c76412498c11">
Fixed the bug of misplaced value.

**Comment by itsdgbro** [comment]
<img width="738" alt="image" src="https://github.com/swastikabasnet/LibraryManagementSystem/assets/94692679/2d9d1fa7-4b09-4cb5-98c2-b9fa4b789fc3">

<img width="649" alt="image" src="https://github.com/swastikabasnet/LibraryManagementSystem/assets/94692679/77546918-16bc-4b1d-8508-676531725ffa">

Fix the quantity negative value.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/3bf1d6cc-d684-419a-9208-d83503898f53)

The book was not being issued. So correct it

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/0c2a31ca-2c20-4552-886e-3dc63c1bbffe)

When editing the book , quantity and availability of the book cannot go below 0. So, correct it as soon as possible

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/9731a4e7-f69d-4fa4-8e37-2aa052cf2f36)
In this signing page, the size and alignment of the box is not matched as highlighted in the above picture. Fix it as soon as possible

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/fbc09bf3-61f3-47c6-a1b6-04b3468e3083)

As highlighted in the above picture. Remember box is little big in size and the font is small. So, fix it.

**Comment by itsdgbro** [comment]
<img width="1280" alt="negative value" src="https://github.com/swastikabasnet/LibraryManagementSystem/assets/94692679/a49a5bae-a8e6-43ef-9edc-e1ea6a4ed39a">

<img width="802" alt="image" src="https://github.com/swastikabasnet/LibraryManagementSystem/assets/94692679/c23ff94c-997d-4cf2-9159-d7684f7ff38e">


Fix all the issues.
