### ISSUE TITLE
As admin, be able to login in the system. (Frontend)

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#5]
Here the admin should be able to  login to the system and do different operation.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/ead73aa1-07e6-438b-b2ed-63f2fe6a1b19)

@sajanshres @abhinaya000  Here the box size of the email and password are not indentical. So work on that.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/25a18671-0df3-49a0-9305-d07459168dc0)

@abhinaya000 @sajanshres The .remember me box looks quite large as well as its font size. So, minimize the box size and the font size
