### ISSUE TITLE
As admin, be able to signup in the system (Frontend)

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#6]
For the new admin to be added by the present admin.

**Comment by itsdgbro** [comment]
Admin can not signup into the System, we do have a default Admin account, To create new Admin accounts, the default Admin can create another admin account from inside the system.

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/ed50ac6f-2766-4378-8237-6e992e6ce683)

@abhinaya000 @sajanshres please change the background image. You can use the image that is being used in the user login

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/22fba3f3-a8cd-4a08-9d7f-3f5feb88d054)

@abhinaya000 @sajanshres @RoDahal as marked in the picture above please correct the css and make it correct by placing it in the same line
