### ISSUE TITLE
As admin, be able to add the books

### ISSUE THREAD

**Issue by swastikabasnet** [swastikabasnet/LibraryManagementSystem#8]
Backend by @itsdgbro 
Frontend by @sajanshres @abhinaya000

**Comment by RekhaTheeng1014** [comment]
![Image](https://github.com/swastikabasnet/LibraryManagementSystem/assets/128008721/9b42774e-7179-48bc-9e6d-82fb263525a2)

The quantity of book cannot be negative. So please work on it and correct the error.
